config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resource :surveys, only: [:new, :create] do
    get :check_answers, on: :member
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/survey.rb
class Survey < ApplicationRecord
  validates :ice_cream, presence: {message: "Choose an ice cream flavour"}
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  def health_check
    render json: {rails: "OK"}, status: :ok
  end
end

app/controllers/surveys_controller.rb
# frozen_string_literal: true

class SurveysController < ApplicationController
  before_action :reset_survey, only: :new, if: -> { session.key?(:survey_id) }

  def new
    @survey = Survey.new
  end

  def create
    @survey = Survey.create(survey_params)
    if @survey.persisted?
      session[:survey_id] = @survey.id
      redirect_to check_answers_surveys_path
    else
      render :new
    end
  end

  def check_answers
    return redirect_to new_surveys_path unless session.key?(:survey_id)
    @survey = Survey.find(session.fetch(:survey_id))
  end

  private

  def survey_params
    params.permit(:ice_cream)
  end

  def reset_survey
    session.delete(:survey_id)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 4.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}", :role  => "alert"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
.container
  %nav.navbar.navbar-dark.bg-inverse
    %ul.nav.navbar-nav.clearfix
      %li.nav-item
        %button.navbar-toggler.hidden-sm-up.nav-link{"aria-controls" => "exCollapsingNavbar2", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#exCollapsingNavbar2", "data-toggle" => "collapse", :type => "button"}
          \ &#9776;
    #exCollapsingNavbar2.collapse.navbar-toggleable-xs
      = link_to "Rails bootstrap", root_path, class: 'navbar-brand'
      %ul.nav.navbar-nav= render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/pages/check-your-answers.html.erb
<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds-from-desktop">

    <h1 class="govuk-heading-xl">Check your answers before sending your choice</h1>

    <dl class="govuk-summary-list govuk-!-margin-bottom-9">
      <div class="govuk-summary-list__row">
        <dt class="govuk-summary-list__key">
          Favourite ice cream
        </dt>
        <dd class="govuk-summary-list__value">
          Vanilla
        </dd>
        <dd class="govuk-summary-list__actions">
          <%= link_to "Change", page_path("form"), class: "govuk-link" %>
        </dd>
      </div>
    </dl>

    <h2 class="govuk-heading-m">Now send your choice</h2>

    <p class="govuk-body">By submitting this notification you are confirming that, to the best of your knowledge, the details you are providing are correct.</p>

    <form action="<%= page_path("confirmation") %>" method="get" novalidate>
      <button class="govuk-button" data-module="govuk-button">
        Accept and send
      </button>
    </form>

  </div>
</div>

app/views/pages/confirmation.html.erb
  <div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
      <div class="govuk-panel govuk-panel--confirmation">
        <h1 class="govuk-panel__title">
          Application complete
        </h1>
        <div class="govuk-panel__body">
          Your reference number<br><strong>HDJ2123F</strong>
        </div>
      </div>

      <p class="govuk-body">We have sent you a confirmation email.</p>

      <h2 class="govuk-heading-m">What happens next</h2>

      <p class="govuk-body">
        We’ve sent your application to Rich.
      </p>
      <p class="govuk-body">
        They will contact you either to confirm your registration, or to ask for more information.
      </p>

      <p class="govuk-body">
        <a href="#" class="govuk-link">What did you think of this service?</a> (takes 30 seconds)
      </p>
    </div>
  </div>

app/views/pages/form.html.erb
<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <form action="<%= page_path("check-your-answers") %>" method="get" novalidate>

      <div class="govuk-form-group">
        <h1 class="govuk-label-wrapper">
          <label class="govuk-label govuk-label--xl" for="ice_cream">
            Question goes here
          </label>
        </h1>
        <div class="govuk-form-group">
          Drop down with and id and name of `ice_cream` goes here
        </div>
      </div>

      <button class="govuk-button" data-module="govuk-button">
        Continue
      </button>

    </form>
  </div>
</div>

app/views/pages/start.html.erb
<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">

    <h1 class="govuk-heading-xl">National ice cream survey</h1>

    <p class="govuk-body">Use this service to:</p>

    <ul class="govuk-list govuk-list--bullet">
      <li>record your favorite ice cream flavour for posterity</li>
      <li>learn how to add stuff to a page and amend tests</li>
      <li>have a go at a red, green, refactor</li>
    </ul>

    <p class="govuk-body">Registering takes around 5 minutes.</p>

    <a href="<%= new_surveys_path %>" role="button" draggable="false" class="govuk-button govuk-!-margin-top-2 govuk-!-margin-bottom-8 govuk-button--start" data-module="govuk-button">
      Start now
      <svg class="govuk-button__start-icon" xmlns="http://www.w3.org/2000/svg" width="17.5" height="19" viewBox="0 0 33 40" aria-hidden="true" focusable="false">
      <path fill="currentColor" d="M0 0h13l20 20-20 20H0l20-20z" />
      </svg>
    </a>

    <h2 class="govuk-heading-m">Before you start</h2>

    <p class="govuk-body">Make sure you are hydrated.</p>
    <p class="govuk-body">You may want snacks.</p>
    <p class="govuk-body">Remember, you can ask for help if you are stuck.</p>

  </div>
</div>

app/views/surveys/check_answers.erb
<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds-from-desktop">

    <h1 class="govuk-heading-xl">Check your answers before sending your choice</h1>

    <dl class="govuk-summary-list govuk-!-margin-bottom-9">
      <div class="govuk-summary-list__row">
        <dt class="govuk-summary-list__key">
          Favourite ice cream
        </dt>
        <dd class="govuk-summary-list__value">
          <%= @survey.ice_cream %>
        </dd>
        <dd class="govuk-summary-list__actions">
          <%= link_to "Change", "#", class: "govuk-link" %>
        </dd>
      </div>
    </dl>

    <h2 class="govuk-heading-m">Now send your choice</h2>

    <p class="govuk-body">By submitting this notification you are confirming that, to the best of your knowledge, the details you are providing are correct.</p>

    <form action="<%= page_path("confirmation") %>" method="get" novalidate>
      <button class="govuk-button" data-module="govuk-button">
        Accept and send
      </button>
    </form>

  </div>
</div>

app/views/surveys/new.html.erb
<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <%= form_with(url: surveys_path, local: true) do %>

      <div class="govuk-form-group">
        <fieldset class="govuk-fieldset">
          <legend class="govuk-fieldset__legend govuk-fieldset__legend--xl">
            <h1 class="govuk-fieldset__heading">
              <%= t("ice_cream_question") %>
            </h1>
          </legend>
          <% @survey.errors[:ice_cream].each do |error| %>
            <span class="govuk-error-message">
              <span class="govuk-visually-hidden">Error:</span> <%= error %>
            </span>
          <% end %>
          <div class="govuk-radios">
            <div class="govuk-radios__item">
              <input class="govuk-radios__input" id="ice_cream" name="ice_cream" type="radio" value="Chocolate">
              <label class="govuk-label govuk-radios__label" for="ice_cream">
                Chocolate
              </label>
            </div>
            <div class="govuk-radios__item">
              <input class="govuk-radios__input" id="ice_cream_2" name="ice_cream" type="radio" value="Vanilla">
              <label class="govuk-label govuk-radios__label" for="ice_cream_2">
                Vanilla
              </label>
            </div>
            <div class="govuk-radios__item">
              <input class="govuk-radios__input" id="ice_cream_3" name="ice_cream" type="radio" value="Raspberry Ripple">
              <label class="govuk-label govuk-radios__label" for="ice_cream_3">
                Raspberry Ripple
              </label>
            </div>
          </div>
        </fieldset>
      </div>

      <button class="govuk-button" data-module="govuk-button">
        Continue
      </button>

    <% end %>
  </div>
</div>